### ISSUE TITLE
关于侧边目录栏的一个小建议

### ISSUE THREAD

**Issue by konosubakonoakua** [summertime-wu/make_cnblogs_better#11]
作者你好，非常感谢你开发了这么一款好用的主题，我在使用过程中发现了一点小问题，希望可以对改进该项目有帮助。
当放大图片，或者图片本身就很大时，右侧的目录导航栏会遮住图片，如下：
![image](https://user-images.githubusercontent.com/42881610/116283179-287f7a80-a7be-11eb-9a05-af3fdc949e0e.png)
有没有办法放大图片时取消显示右侧menu（自己试了下，对css不熟，没弄好）

**Comment by konosubakonoakua** [comment]
改一下右边栏的 z-index就行了

**Comment by summertime-wu** [comment]
是的，其实可以提个pr 哈哈
之前把侧边目录设为 z-index 999 是因为为了适配手机端，现在看来好像没有太大必要😂
