### ISSUE TITLE
在SimpleMemory主题之后设置本主题失效

### ISSUE THREAD

**Issue by Johnsonzcode** [summertime-wu/make_cnblogs_better#14]
按照文档教程添加
效果为这样，不知道怎么更正
![image](https://user-images.githubusercontent.com/40168263/127162857-65420d06-eaa0-466c-80ba-81e0da195f1a.png)

**Comment by Johnsonzcode** [comment]
你好，我可太喜欢这个主题了，球球了

**Comment by summertime-wu** [comment]
亲，先把主题设置成 BlueSky

**Comment by Johnsonzcode** [comment]
设置过了


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月14日 23:08:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [summertime-wu/make_cnblogs_better] 在SimpleMemory主题之后设置本主题失效 (#14)




 
亲，先把主题设置成 BlueSky
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by summertime-wu** [comment]
来个地址我康康

**Comment by Johnsonzcode** [comment]
好的，https://www.cnblogs.com/johnsonzzz/，现在我看问题变成了不居中

**Comment by Johnsonzcode** [comment]
你好，我找到原因了，因为禁用了默认，习惯性的禁用了，其他博主的主题一般都禁用了，粗心了。

**Comment by summertime-wu** [comment]
好的
