### ISSUE TITLE
样式无法适配问题

### ISSUE THREAD

**Issue by FanxwGit** [summertime-wu/make_cnblogs_better#18]
有些样式没有适配上，好奇怪...求助
https://www.cnblogs.com/Fanxw
![image](https://user-images.githubusercontent.com/78842723/202199967-fc5be978-7c5e-4f0e-ab6f-8d47d265042c.png)

**Comment by summertime-wu** [comment]
> 有些样式没有适配上，好奇怪...求助 https://www.cnblogs.com/Fanxw ![image](https://user-images.githubusercontent.com/78842723/202199967-fc5be978-7c5e-4f0e-ab6f-8d47d265042c.png)

你好像没有基于 [BlueSky](https://www.cnblogs.com/SkinUser.aspx?SkinName=BlueSky) 这个主题
![image](https://user-images.githubusercontent.com/31026540/202395283-c2ead475-f0bd-4ba6-962d-95f84532a7a3.png)

**Comment by FanxwGit** [comment]
> > 有些样式没有适配上，好奇怪...求助 https://www.cnblogs.com/Fanxw ![image](https://user-images.githubusercontent.com/78842723/202199967-fc5be978-7c5e-4f0e-ab6f-8d47d265042c.png)
> 
> 你好像没有基于 [BlueSky](https://www.cnblogs.com/SkinUser.aspx?SkinName=BlueSky) 这个主题 ![image](https://user-images.githubusercontent.com/31026540/202395283-c2ead475-f0bd-4ba6-962d-95f84532a7a3.png)

感谢 已解决。不小心禁用了原来的css
