### ISSUE TITLE
Markdown无符号列表显示不正常

### ISSUE THREAD

**Issue by QuintinLiu** [Summertime-Wu/make_cnblogs_better#5]
您好，想问一下您的在您的博客上面Markdown无符号列表显示正常么？在我的博客里面无符号列表的每一项都换行了，还有斜体字也显示不出来
![微信截图_20190901193808](https://user-images.githubusercontent.com/40739281/64075864-151dc280-ccf0-11e9-8940-a5a017a4c6dd.jpg)

**Comment by Summertime-Wu** [comment]
刚测试了下，是有这两个问题的，非常感谢你的反馈～

应该是我的自定义样式导致了这个错误

最近有点儿忙，不能及时处理，假如你有兴趣的话可以提个 pr ：)

**Comment by QuintinLiu** [comment]
我最后发现是bluesky这个主题本身的错误，我把所有的自定义都去除后，还是有那个问题

随后我又换了另一个主题simple memory，显示是正常的，然后我是在simple memory这个主题上面进行了一些调整

**Comment by Summertime-Wu** [comment]
nice！

我将在下个版本修复它
你感兴趣的话也可以参与进来
