### ISSUE TITLE
请求

### ISSUE THREAD

**Issue by guangzan** [Summertime-Wu/make_cnblogs_better#6]
您好，我是博客园皮肤脚手架 awescnb 作者，我写了一个项目，它可以快速构建、切换、安装博客园皮肤，已有近百人使用它。十分喜欢您的皮肤，看到您在 github 将它开源，我可以将您的皮肤集成进我的项目中吗？会在项目中附上您的链接。QQ群：541802647 

respect ！

**Comment by Summertime-Wu** [comment]
当然可以，非常欢迎
