### ISSUE TITLE
你好 请教一个问题

### ISSUE THREAD

**Issue by yhybulider** [Summertime-Wu/make_cnblogs_better#7]
我发现评论不了文章
![image.png](https://i.loli.net/2020/06/08/FoxrGKXcIiVDpQa.png)
这个是屏蔽底下的提交按钮了吗，因为我借鉴你的自定义，大哥这个该怎么修改？谢谢了

**Comment by yhybulider** [comment]
我找到了解决 原来直接alt enter也可以

**Comment by Summertime-Wu** [comment]
这个是因为博客园做了调整 导致使用我的样式变形了 原本是有一个精致的按钮的...

问题先开着吧，等抽空适配一下

**Comment by yhybulider** [comment]
好 谢谢

**Comment by Summertime-Wu** [comment]
已适配～
